name: CICD

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t vishakhappu/generative-server ./api
      - name: Publish image to docker hub
        run: docker push vishakhappu/generative-server:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2-server]
    steps:
      - name: Pull image from docker hub
        run: docker pull vishakhappu/generative-server:latest
      - name: Delete old container
        run: docker rm -f generative-container
      - name: Run docker container
        run: |
          docker run -d -p 8000:8000 --name generative-container \
          -e MONGODBURL='${{ secrets.MONGODBURL }}' \
          -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
          -e NODE_ENV='${{ secrets.NODE_ENV }}' \
          -e BASE_URL='${{ secrets.BASE_URL }}' \
          -e CLIENT_URL='${{ secrets.CLIENT_URL }}' \
          -e EMAIL_USER='${{ secrets.EMAIL_USER }}' \
          -e APP_PASSWORD='${{ secrets.APP_PASSWORD }}' \
          vishakhappu/generative-server 
             


        